const data = [
  {
    id: 1,
    name: "ALINA KHAN",
    username: "Allie030",
    email: "filma@example.com",
    joinedOn: "September 9, 2013",
    sports: "Tennis",
    speed: "20",
    jump: "18",
    dance: "40",
    forwardSkate: "40",
    backwardSkate: "40",
  },
  {
    id: 2,
    name: "ALINA ALI",
    username: "Allie030",
    email: "filma@example.com",
    joinedOn: "September 9, 2013",
    sports: "Tennis",
    speed: "20",
    jump: "18",
    dance: "40",
    forwardSkate: "40",
    backwardSkate: "40",
  },
  {
    id: 3,
    name: "EMMA STONE",
    username: "Allie030",
    email: "filma@example.com",
    joinedOn: "September 9, 2013",
    sports: "Tennis",
    speed: "20",
    jump: "18",
    dance: "40",
    forwardSkate: "40",
    backwardSkate: "40",
  },
  {
    id: 5,
    name: "EMMA STONE",
    username: "Allie030",
    email: "filma@example.com",
    joinedOn: "September 9, 2013",
    sports: "Tennis",
    speed: "20",
    jump: "18",
    dance: "40",
    forwardSkate: "40",
    backwardSkate: "40",
  },
  {
    id: 6,
    name: "EMMA STONE",
    username: "Allie030",
    email: "filma@example.com",
    joinedOn: "September 9, 2013",
    sports: "Tennis",
    speed: "20",
    jump: "18",
    dance: "40",
    forwardSkate: "40",
    backwardSkate: "40",
  },
  // Add more data objects as needed
];
export default data;
